### PR TITLE
Update config.xml

### PR DESCRIPTION
**Pull request by infabo**
Module name is case-sensitive

### CODE REVIEW

**Comment by jakubpolomsky** [comment]
Hello,

thank you for your time you invested in this pull request, but may I ask what was the problem and how was this a solution to it? We didn't notice any issues in our automated tests, I clicked through the routines manually and still didn't notice anything. Could you please elaborate  the cause of your pull request a little?

Excuse us for the delay

Kind regards

**Comment by jakubpolomsky** [comment]
After reviewing the changes and trying the code, I'd suggest not to do this in a plugin. The module name might be case sensitive but it surely works as it is supposed to. Changing the name caused multiple errors in existing instances of magento as well as in new docker instances. Therefore closing this request.

Thanks once again for your time

**Comment by infabo** [comment]
@jakubpolomsky what kind of "multiple errors" did it cause? This is convention and is directly related to the config node here -> https://github.com/wirecard/magento-wcp/blob/master/app/etc/modules/Wirecard_CheckoutPage.xml

Oh, wait....you did use the right casing there, but not in config.xml. So what are your concerns actually about?

**Comment by jakubpolomsky** [comment]
Steps to reproduce:

Scenario 1
1. install plugin
2. clear caches
3. configure
4. test payment
5. update plugin
6. clear caches
7. error, magento instance damaged

Scenario 2
1. install updated plugin
2. clear caches
3. error, magento instance damaged

**Comment by infabo** [comment]
With you wrong casing it is not possible for Magento, to detect the version of the plugin. Therefore not writing an entry to core_resource.

**Comment by infabo** [comment]
> error, magento instance damaged

"Damaged" and "broken" are always the most accurate descriptions of errors. I'm really sorry to say this.

**Comment by jakubpolomsky** [comment]
Of course, thank you for pointing out.

`Running This Upgrade: Mage_Eav_Model_Entity_Setup `

Instance not usable. Not working, thus broken or damaged.

**Comment by infabo** [comment]
@jakubpolomsky Maybe ask @Trimnosh why he did add the DIE statement in the setup script.

https://github.com/wirecard/magento-wcp/blame/master/app/code/community/Wirecard/CheckoutPage/sql/wirecard_checkoutpage_setup/mysql4-install-4.0.0.php#L33

**Comment by infabo** [comment]
So once you resolved and discussed the setup-script in your team ("why", "who" or "wtf?"), maybe you can still accept my PR. Feel free to modify it, but please keep the **casing** right!

**Comment by jakubpolomsky** [comment]
Thank you, I will look into this today.

**Pull request merged**
